### ISSUE TITLE
Build error on old SDK

### ISSUE THREAD

**Issue by IRooc** [cmuratori/termbench#1]
According to my registry I have version `6.3..9600` (yes double dot) of the sdk.

So the ENABLE_VIRTUAL_TERMINAL_PROCESSING is not defined,  I slapped in this after include windows.h and it worked fine.
```
#ifndef ENABLE_VIRTUAL_TERMINAL_PROCESSING
#define ENABLE_VIRTUAL_TERMINAL_PROCESSING 0x0004
#endif
```

Still slow though...

**Comment by cmuratori** [comment]
This might be fixed now, with v1.

\- Casey

**Comment by IRooc** [comment]
Yep!
